Repository J1P5/Meerket__BE, pull requests merged in 2024-12, with the labels that each got.

#10 중고물픔을 등록할 수 있다.
  meerket/meerket-application/build.gradle
  meerket/meerket-application/src/main/java/org/j1p5/api/MeerketApplication.java
  meerket/meerket-application/src/main/java/org/j1p5/api/product/api/ProductController.java
  meerket/meerket-application/src/main/java/org/j1p5/api/product/converter/MultipartFileConverter.java
  meerket/meerket-application/src/main/java/org/j1p5/api/product/dto/request/ProductRequestDto.java
  meerket/meerket-application/src/test/java/org/j1p5/api/product/api/ProductControllerTest.java
  meerket/meerket-common/src/main/java/org/j1p5/common/exception/GlobalErrorCode.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/auth/area/repository/AreaAuthRepository.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/comment/repository/CommentRepository.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/image/entitiy/ImageEntity.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/dto/ProductInfo.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/entity/ProductEntity.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/exception/ProductException.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/repository/ProductRepository.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/repository/querydsl/ProductRepositoryCustom.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/service/ImageService.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/service/ProductAppender.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/service/ProductService.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/service/UserReader.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/service/UserRegionauth.java
  meerket/meerket-infrastructure/build.gradle
  meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/global/s3/ImageServiceImpl.java
  meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/global/s3/ImageValidator.java
  meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/global/s3/S3Config.java
  meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/global/s3/exception/S3ErrorCode.java
Labels: enhancement, ⚙ Chore, ✨ Feature

#18 Feat/#12 read product
  meerket/meerket-application/src/main/java/org/j1p5/api/global/config/CursorArgumentResolver.java
  meerket/meerket-application/src/main/java/org/j1p5/api/global/config/WebConfig.java
  meerket/meerket-application/src/main/java/org/j1p5/api/product/api/ProductController.java
  meerket/meerket-common/src/main/java/org/j1p5/common/annotation/CursorDefault.java
  meerket/meerket-common/src/main/java/org/j1p5/common/dto/Cursor.java
  meerket/meerket-common/src/main/java/org/j1p5/common/dto/CursorResult.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/global/config/QuerydslConfig.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/image/entitiy/ImageEntity.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/dto/MyLocationInfo.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/dto/ProductResponseInfo.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/repository/ProductRepository.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/repository/querydsl/ProductRepositoryCustom.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/repository/querydsl/ProductRepositoryCustomImpl.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/service/ActivityAreaReader.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/service/ProductService.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/service/UserLocationNameReader.java
Labels: enhancement, ⚙ Chore, ✨ Feature

#30 Refactor/#17 product refactor
  meerket/meerket-application/build.gradle
  meerket/meerket-application/src/main/java/org/j1p5/MeerketApplication.java
  meerket/meerket-application/src/main/java/org/j1p5/api/product/controller/ProductController.java
  meerket/meerket-application/src/main/java/org/j1p5/api/product/converter/MultipartFileConverter.java
  meerket/meerket-application/src/main/java/org/j1p5/api/product/dto/request/ProductRequestDto.java
  meerket/meerket-application/src/test/java/org/j1p5/api/product/controller/ProductControllerTest.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/image/entitiy/ImageEntity.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/service/ProductService.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/service/RegionAuthHandler.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/service/UserReader.java
  meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/global/s3/ImageServiceImpl.java
  meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/global/s3/ImageValidator.java
  meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/global/s3/exception/S3ErrorCode.java
Labels: enhancement

#31 Feat/#19 product read detail
  meerket/meerket-application/src/main/java/org/j1p5/api/global/annotation/LoginUser.java
  meerket/meerket-application/src/main/java/org/j1p5/api/global/annotation/LoginUserArgumentResolver.java
  meerket/meerket-application/src/main/java/org/j1p5/api/global/config/CorsConfig.java
  meerket/meerket-application/src/main/java/org/j1p5/api/global/config/SecurityConfig.java
  meerket/meerket-application/src/main/java/org/j1p5/api/global/config/WebConfig.java
  meerket/meerket-application/src/main/java/org/j1p5/api/product/controller/ProductController.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/dto/ProductLocationInfo.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/dto/ProductResponseDetailInfo.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/dto/SellerInfo.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/entity/ProductEntity.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/exception/ProductException.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/service/ProductService.java
Labels: ✨ Feature

#32 Feat/#22 product update
  meerket/meerket-application/src/main/java/org/j1p5/api/global/config/WebConfig.java
  meerket/meerket-application/src/main/java/org/j1p5/api/product/controller/ProductController.java
  meerket/meerket-application/src/main/java/org/j1p5/api/product/dto/request/ProductCreateRequestDto.java
  meerket/meerket-application/src/main/java/org/j1p5/api/product/dto/request/ProductUpdateRequest.java
  meerket/meerket-application/src/test/java/org/j1p5/api/product/controller/ProductControllerTest.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/dto/ProductUpdateInfo.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/entity/ProductEntity.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/exception/ProductException.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/service/PointConverter.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/service/ProductService.java
Labels: ✨ Feature

#33 Feat/#26 delete product
  meerket/meerket-application/src/main/java/org/j1p5/api/product/controller/ProductController.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/entity/ProductEntity.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/exception/ProductException.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/repository/querydsl/ProductRepositoryCustomImpl.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/service/ProductService.java
Labels: ✨ Feature

#40 Feat/#39 chat controller
  meerket/build.gradle
  meerket/meerket-application/build.gradle
  meerket/meerket-application/src/main/java/org/j1p5/api/auth/api/OauthController.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auth/service/OauthLoginUsecase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auth/service/OauthSenderService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auth/service/OauthService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/config/WebSocketConfig.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/controller/ChatController.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/dto/ChatRoomBasicInfo.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/dto/ChatRoomType.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/dto/OtherProfile.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/dto/request/ChatMessageRequest.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/dto/response/ChatMessageResponse.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/dto/response/ChatRoomEnterResponse.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/dto/response/ChatRoomInfoResponse.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/dto/response/ChatSocketMessageResponse.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/dto/response/CreateChatRoomResponse.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/event/WebSocketEventListener.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/exception/ChatException.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/ChatMessageService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/ChatRoomService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/usecase/CreateChatRoomUseCase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/usecase/EnterChatRoomUseCase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/usecase/ExitChatRoomUseCase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/usecase/GetChatMessageUseCase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/usecase/GetUserChatRoomsUseCase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/usecase/SendChatMessageUseCase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/fcm/FcmService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/global/config/SecurityConfig.java
  meerket/meerket-application/src/main/java/org/j1p5/api/global/handler/CustomAccessDeniedHandler.java
  meerket/meerket-application/src/main/java/org/j1p5/api/global/handler/CustomAuthenticationEntryPoint.java
  meerket/meerket-domain/build.gradle
  meerket/meerket-domain/src/main/java/org/j1p5/domain/chat/config/MongoConfig.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/chat/entity/ChatMessageEntity.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/chat/entity/ChatRoomEntity.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/chat/repository/ChatMessageRepository.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/chat/repository/ChatRoomRepository.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/chat/vo/MessageInfo.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/fcm/FcmSender.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/fcm/entity/FcmTokenEntity.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/fcm/repository/FcmTokenRepository.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/global/config/JpaConfig.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/service/ProductService.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/service/ProductUserReader.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/redis/RedisService.java
  meerket/meerket-domain/src/main/resources/application-domain.yml
  meerket/meerket-domain/src/test/java/org/j1p5/domain/auth/OauthSenderTest.java
  meerket/meerket-domain/src/test/java/org/j1p5/domain/auth/OauthServiceTest.java
  meerket/meerket-infrastructure/build.gradle
  meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/fcm/FcmSenderImpl.java
  meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/fcm/config/FirebaseConfig.java
  meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/redis/RedisServiceImpl.java
  meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/redis/config/RedisConfig.java
Labels: 예찬, ⚙ Chore, ✨ Feature

#47 Feat/#16 register nickname, image
  meerket/build.gradle
  meerket/meerket-application/src/main/java/org/j1p5/api/global/excpetion/WebErrorCode.java
  meerket/meerket-application/src/main/java/org/j1p5/api/product/converter/MultipartFileConverter.java
  meerket/meerket-application/src/main/java/org/j1p5/api/user/controller/UserController.java
  meerket/meerket-application/src/main/java/org/j1p5/api/user/dto/NameRegisterRequest.java
  meerket/meerket-application/src/main/java/org/j1p5/api/user/exception/NicknameAlreadyExistException.java
  meerket/meerket-application/src/main/java/org/j1p5/api/user/exception/UserNotFoundException.java
  meerket/meerket-application/src/main/java/org/j1p5/api/user/service/UserRegisterService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/user/usecase/UserImageRegisterUsecase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/user/usecase/UserNameRegisterUsecase.java
  meerket/meerket-application/src/main/resources/application.yml
  meerket/meerket-domain/src/main/java/org/j1p5/domain/user/UserImageClient.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/user/entity/EmdArea.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/user/entity/UserEntity.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/user/repository/UserRepository.java
  meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/global/s3/ImageServiceImpl.java
  meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/global/s3/S3Config.java
  meerket/meerket-infrastructure/src/main/resources/application-infrastructure.yml
Labels: 승주, ✨ Feature

#41 [Feat] 댓글을 생성한다
  meerket/meerket-application/src/main/java/org/j1p5/api/comment/controller/CommentController.java
  meerket/meerket-application/src/main/java/org/j1p5/api/comment/dto/request/CommentCreateRequestDto.java
  meerket/meerket-application/src/main/java/org/j1p5/api/comment/exception/CommentErrorCode.java
  meerket/meerket-application/src/main/java/org/j1p5/api/comment/service/CommentService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/comment/usecase/CommentCreateUsecase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/global/config/SecurityConfig.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/comment/entity/CommentEntity.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/service/ProductService.java
Labels: enhancement, ✨ Feature

#52 Feat/#46 chat exception
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/controller/ChatController.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/dto/response/ChatSocketMessageResponse.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/exception/ChatException.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/ChatMessageService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/ChatRoomService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/usecase/EnterChatRoomUseCase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/usecase/ExitChatRoomUseCase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/usecase/GetChatMessageUseCase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/usecase/SendChatMessageUseCase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/fcm/FcmService.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/fcm/entity/FcmTokenEntity.java
  meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/fcm/FcmSenderImpl.java
  meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/fcm/exception/FcmException.java
Labels: enhancement, 예찬, ✨ Feature

#66 [Refactor] : 로그인 로직 리팩터링
  meerket/meerket-application/src/main/java/org/j1p5/api/activityArea/service/ActivityAreaService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auth/AuthManager.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auth/api/OauthController.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auth/dto/LoginResponse.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auth/dto/SessionInfo.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auth/service/OauthLoginUsecase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auth/service/OauthService.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/activityArea/repository/ActivityAreaRepository.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/user/UserInfo.java
Labels: 승주, 🔨 Refactor

#78 keyword로 상품을 조회할 수 있다
  meerket/meerket-application/src/main/java/org/j1p5/api/product/controller/ProductController.java
  meerket/meerket-application/src/main/java/org/j1p5/api/product/exception/ProductException.java
  meerket/meerket-application/src/main/java/org/j1p5/api/product/service/ProductService.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/repository/querydsl/ProductRepositoryCustom.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/repository/querydsl/ProductRepositoryCustomImpl.java
Labels: ✨ Feature

#81 [Feat] : 조기마감 구현
  meerket/meerket-application/src/main/java/org/j1p5/api/product/controller/ProductController.java
  meerket/meerket-application/src/main/java/org/j1p5/api/product/dto/response/CloseEarlyResponseDto.java
  meerket/meerket-application/src/main/java/org/j1p5/api/product/exception/ProductException.java
  meerket/meerket-application/src/main/java/org/j1p5/api/product/service/ProductService.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/dto/ProductResponseDetailInfo.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/entity/ProductEntity.java
Labels: ✨ Feature

#82 Feat/#65 입찰 생성,조회,수정 기능구현과 Quartz 초기 설정
  meerket/meerket-application/build.gradle
  meerket/meerket-application/src/main/java/org/j1p5/api/auction/controller/AuctionController.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auction/dto/request/PlaceBidRequest.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auction/dto/request/UpdateBidPriceRequest.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auction/dto/response/BidHistoryResponse.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auction/dto/response/GetCompletedPurchasesResponse.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auction/dto/response/PlaceBidResponse.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auction/dto/response/UpdateBidPriceResponse.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auction/exception/AuctionException.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auction/job/AuctionClosingJob.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auction/quartz/QuartzService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auction/service/AuctionService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auction/service/usecase/CancelBidUseCase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auction/service/usecase/GetBiddingHistoryUseCase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auction/service/usecase/GetCompletedPurchasesUseCase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auction/service/usecase/PlaceBidUseCase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auction/service/usecase/UpdateBidPriceUseCase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/controller/ChatController.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/dto/request/ChatMessageRequest.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/dto/response/ChatRoomInfoResponse.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/event/WebSocketEventListener.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/ChatRoomService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/usecase/SendChatMessageUseCase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/fcm/FcmService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/product/service/EmdNameReader.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/auction/entity/AuctionEntity.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/auction/entity/AuctionStatus.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/auction/repository/AuctionRepository.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/fcm/FcmSender.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/redis/RedisService.java
  meerket/meerket-infrastructure/build.gradle
  meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/fcm/FcmSenderImpl.java
  meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/fcm/exception/FcmException.java
  meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/quartz/config/AutowiringSpringBeanJobFactory.java
  meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/quartz/config/QuartzConfig.java
  meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/redis/RedisServiceImpl.java
  meerket/meerket-infrastructure/src/main/resources/application-infrastructure.yml
Labels: 예찬, ⚙ Chore, ✨ Feature

#86 [hotfix] : 프론트 연계 cors, 세션 쿠키 설정 변경
  meerket/meerket-application/src/main/java/org/j1p5/api/global/config/CorsConfig.java
  meerket/meerket-application/src/main/resources/application.yml
Labels: bug, 승주

#94 refactor : ChatCustomRepository 생성하여 리팩토링
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/ChatMessageService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/ChatRoomService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/usecase/EnterChatRoomUseCase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/usecase/ExitChatRoomUseCase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/usecase/GetUserChatRoomsUseCase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/usecase/SendChatMessageUseCase.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/chat/repository/ChatMessageRepository.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/chat/repository/ChatRoomRepository.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/chat/repository/custom/ChatMessageCustomRepository.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/chat/repository/custom/ChatMessageCustomRepositoryImpl.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/chat/repository/custom/ChatRoomCustomRepository.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/chat/repository/custom/ChatRoomCustomRepositoryImpl.java
Labels: enhancement, 예찬, 🔨 Refactor

#113 Refactor/#112 chat room info count
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/dto/ChatRoomBasicInfo.java
  meerket/meerket-application/src/main/java/org/j1p5/api/chat/service/usecase/EnterChatRoomUseCase.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/chat/repository/custom/ChatMessageCustomRepositoryImpl.java
Labels: 예찬, ✨ Feature, 🔨 Refactor

#115 Fix/#114
  meerket/meerket-application/src/main/java/org/j1p5/api/auction/service/usecase/PlaceBidUseCase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/comment/dto/response/CommentReadResponseDto.java
Labels: bug

#131 [Feat] 유저 차단 기능 구현
  meerket/meerket-application/src/main/java/org/j1p5/api/block/controller/BlockController.java
  meerket/meerket-application/src/main/java/org/j1p5/api/block/dto/BlockDeleteRequest.java
  meerket/meerket-application/src/main/java/org/j1p5/api/block/dto/BlockRegisterRequest.java
  meerket/meerket-application/src/main/java/org/j1p5/api/block/service/BlockDeleteService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/block/service/BlockReadService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/block/service/BlockRegisterService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/block/validator/BlockValidator.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/block/BlockUserInfo.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/block/entity/BlockEntity.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/block/repository/BlockRepository.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/user/repository/UserRepository.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/user/repository/custom/UserRepositoryCustom.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/user/repository/custom/UserRepositoryCustomImpl.java
Labels: 승주, ✨ Feature

#136 [refactor] 차단 등록 요청 프로퍼티 네이밍 수정
  meerket/meerket-application/src/main/java/org/j1p5/api/block/controller/BlockController.java
  meerket/meerket-application/src/main/java/org/j1p5/api/block/dto/BlockRegisterRequest.java
Labels: 승주, 🔨 Refactor

#135 [refactor] 소셜 로그인 시 이메일 수집 안하도록 수정
  meerket/meerket-application/src/main/java/org/j1p5/api/auth/service/OauthService.java
  meerket/meerket-application/src/test/java/org/j1p5/api/auth/AuthFixture.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/auth/dto/OauthProfile.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/user/entity/UserEntity.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/user/repository/UserRepository.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/user/service/UserAppender.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/user/service/UserReader.java
  meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/kakao/dto/KakaoProfile.java
  meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/naver/dto/NaverProfile.java
Labels: 승주, 🔨 Refactor

#133 [Refactor] 유저 차단 후 조회 필터링
  meerket/meerket-application/src/main/java/org/j1p5/api/comment/dto/response/CommentReadResponseDto.java
  meerket/meerket-application/src/main/java/org/j1p5/api/comment/service/CommentService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/comment/usecase/CommentReadUsecase.java
  meerket/meerket-application/src/main/java/org/j1p5/api/product/service/ProductService.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/comment/CommentInfo.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/comment/repository/querydsl/CommentRepositoryCustomImpl.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/repository/querydsl/ProductRepositoryCustom.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/repository/querydsl/ProductRepositoryCustomImpl.java
Labels: 승주, 🔨 Refactor

#139 [refactor] : 차단 기능 동작을 위해 댓글 조회에 유저 id추가
  meerket/meerket-application/src/main/java/org/j1p5/api/comment/dto/CommentMemeberDto.java
  meerket/meerket-application/src/main/java/org/j1p5/api/comment/dto/response/CommentReadResponseDto.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/comment/CommentInfo.java
Labels: 승주, 🔨 Refactor

#138 [Feat] 신고 등록
  meerket/meerket-application/src/main/java/org/j1p5/api/comment/exception/CommentNotFoundException.java
  meerket/meerket-application/src/main/java/org/j1p5/api/product/exception/ProductNotFoundException.java
  meerket/meerket-application/src/main/java/org/j1p5/api/report/controller/ReportController.java
  meerket/meerket-application/src/main/java/org/j1p5/api/report/dto/ReportRegisterRequest.java
  meerket/meerket-application/src/main/java/org/j1p5/api/report/service/ReportRegisterService.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/global/exception/DomainErrorCode.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/report/ReportImageClient.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/report/ReportInfo.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/report/entity/ReportEntity.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/report/entity/ReportTarget.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/report/entity/ReportType.java
  meerket/meerket-infrastructure/src/main/java/org/j1p5/infrastructure/global/s3/ImageServiceImpl.java
Labels: 승주, ✨ Feature

#141 [Feat] 회원탈퇴 기능 구현
  meerket/meerket-application/src/main/java/org/j1p5/api/activityArea/service/ActivityAreaService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/areaAuth/service/AreaAuthService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/auction/service/AuctionService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/block/service/BlockDeleteService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/comment/dto/response/CommentReadResponseDto.java
  meerket/meerket-application/src/main/java/org/j1p5/api/comment/service/CommentService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/product/service/ProductImageService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/product/service/ProductService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/report/service/ReportService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/user/controller/UserController.java
  meerket/meerket-application/src/main/java/org/j1p5/api/user/service/UserWithdrawService.java
  meerket/meerket-application/src/main/java/org/j1p5/api/user/usecase/UserWithdrawUsecase.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/activityArea/entity/ActivityArea.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/areaAuth/entity/AreaAuthEntity.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/auction/entity/AuctionEntity.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/auction/repository/AuctionRepository.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/block/entity/BlockEntity.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/comment/CommentInfo.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/comment/repository/CommentRepository.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/history/search/entity/SearchHistory.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/image/entitiy/ImageEntity.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/image/repository/ImageRepository.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/entity/ProductEntity.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/repository/ProductRepository.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/repository/querydsl/ProductRepositoryCustomImpl.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/report/entity/ReportEntity.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/report/repository/ReportRepository.java
  meerket/meerket-domain/src/main/java/org/j1p5/domain/user/entity/UserEntity.java
Labels: 승주, ✨ Feature

#148 [Hotfix] 상품 조회 시 차단 유저 null 에러 픽스
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/repository/querydsl/ProductRepositoryCustomImpl.java
Labels: bug, 승주

#149 [Hotfix] : 상품 조회 query 에러 수정
  meerket/meerket-domain/src/main/java/org/j1p5/domain/product/repository/querydsl/ProductRepositoryCustomImpl.java
Labels: bug, 승주
